### ISSUE TITLE
你好 请问大概几月能开源全部代码

### ISSUE THREAD

**Issue by OvOYu** [water-wbq/DSTCGCN#1]
我对你们的研究很感兴趣，非常感谢

**Comment by water-wbq** [comment]
谢谢关注！
我们的第一个版本已经发布在：https://arxiv.org/pdf/2307.00518.pdf
目前我们结合审稿意见对该版本做了迭代
会在8月份开放完整的代码

@misc{wu2023dstcgcn,
      title={DSTCGCN: Learning Dynamic Spatial-Temporal Cross Dependencies for Traffic Forecasting}, 
      author={Binqing Wu and Ling Chen},
      year={2023},
      eprint={2307.00518},
      archivePrefix={arXiv},
      primaryClass={cs.LG}
}
